# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-29 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icon',
            options={'verbose_name': '\u05d0\u05d9\u05d9\u05e7\u05d5\u05df', 'verbose_name_plural': '\u05d0\u05d9\u05d9\u05e7\u05d5\u05e0\u05d9\u05dd'},
        ),
    ]
