# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-07 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('icons', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('calendarevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.CalendarEvent')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name=b'Source URL')),
                ('uid', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'UID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ('start_date', 'title'),
                'verbose_name': '\u05d7\u05d2',
                'verbose_name_plural': '\u05d7\u05d2\u05d9\u05dd',
            },
            bases=('main.calendarevent',),
        ),
        migrations.CreateModel(
            name='OneTimeEvent',
            fields=[
                ('calendarevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.CalendarEvent')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
            options={
                'ordering': ('start_date', 'title'),
                'verbose_name': '\u05d0\u05d9\u05e8\u05d5\u05e2 \u05d7\u05d3 \u05e4\u05e2\u05de\u05d9',
                'verbose_name_plural': '\u05d0\u05d9\u05e8\u05d5\u05e2\u05d9\u05dd \u05d7\u05d3 \u05e4\u05e2\u05de\u05d9\u05d9\u05dd',
            },
            bases=('main.calendarevent',),
        ),
        migrations.CreateModel(
            name='SpecialDay',
            fields=[
                ('calendarevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.CalendarEvent')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)])),
                ('day', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)])),
            ],
            options={
                'ordering': ('month', 'day'),
                'verbose_name': '\u05d9\u05d5\u05dd \u05de\u05d9\u05d5\u05d7\u05d3',
                'verbose_name_plural': '\u05d9\u05de\u05d9\u05dd \u05de\u05d9\u05d5\u05d7\u05d3\u05d9\u05dd',
            },
            bases=('main.calendarevent',),
        ),
        migrations.CreateModel(
            name='WeeklyActivity',
            fields=[
                ('calendarevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.CalendarEvent')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('day_of_the_week', models.PositiveSmallIntegerField(choices=[(6, '\u05e8\u05d0\u05e9\u05d5\u05df'), (0, '\u05e9\u05e0\u05d9'), (1, '\u05e9\u05dc\u05d9\u05e9\u05d9'), (2, '\u05e8\u05d1\u05d9\u05e2\u05d9'), (3, '\u05d7\u05de\u05d9\u05e9\u05d9'), (4, '\u05e9\u05d9\u05e9\u05d9'), (5, '\u05e9\u05d1\u05ea')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('except_holidays', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('day_of_the_week', 'title'),
                'verbose_name': '\u05e4\u05e2\u05d9\u05dc\u05d5\u05ea \u05e9\u05d1\u05d5\u05e2\u05d9\u05ea',
                'verbose_name_plural': '\u05e4\u05e2\u05d9\u05dc\u05d5\u05d9\u05d5\u05ea \u05e9\u05d1\u05d5\u05e2\u05d9\u05d5\u05ea',
            },
            bases=('main.calendarevent',),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icons.Icon'),
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together=set([('source_url', 'uid')]),
        ),
    ]
