# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-07 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CalendarEvent')),
            ],
            options={
                'verbose_name': '\u05d4\u05d9\u05e7\u05e8\u05d5\u05ea',
                'verbose_name_plural': '\u05d4\u05d9\u05e7\u05e8\u05d5\u05d9\u05d5\u05ea',
            },
        ),
        migrations.AlterUniqueTogether(
            name='occurrence',
            unique_together=set([('event', 'date')]),
        ),
    ]
