# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-07 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161007_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occurrence',
            options={'ordering': ('date',), 'verbose_name': '\u05d4\u05d9\u05e7\u05e8\u05d5\u05ea', 'verbose_name_plural': '\u05d4\u05d9\u05e7\u05e8\u05d5\u05d9\u05d5\u05ea'},
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
