# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-09 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20161007_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimeevent',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
