# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-29 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20161009_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyactivity',
            name='except_holidays',
        ),
        migrations.AddField(
            model_name='weeklyactivity',
            name='include_holidays',
            field=models.BooleanField(default=False, verbose_name='\u05db\u05d5\u05dc\u05dc \u05d9\u05de\u05d9 \u05d7\u05d2'),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='title',
            field=models.CharField(max_length=200, verbose_name='\u05db\u05d5\u05ea\u05e8\u05ea'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='end_date',
            field=models.DateField(verbose_name='\u05e1\u05d9\u05d5\u05dd'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='start_date',
            field=models.DateField(verbose_name='\u05d4\u05ea\u05d7\u05dc\u05d4'),
        ),
        migrations.AlterField(
            model_name='specialday',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], verbose_name='\u05d9\u05d5\u05dd'),
        ),
        migrations.AlterField(
            model_name='specialday',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='\u05d7\u05d5\u05d3\u05e9'),
        ),
        migrations.AlterField(
            model_name='weeklyactivity',
            name='day_of_the_week',
            field=models.PositiveSmallIntegerField(choices=[(6, '\u05e8\u05d0\u05e9\u05d5\u05df'), (0, '\u05e9\u05e0\u05d9'), (1, '\u05e9\u05dc\u05d9\u05e9\u05d9'), (2, '\u05e8\u05d1\u05d9\u05e2\u05d9'), (3, '\u05d7\u05de\u05d9\u05e9\u05d9'), (4, '\u05e9\u05d9\u05e9\u05d9'), (5, '\u05e9\u05d1\u05ea')], verbose_name='\u05d9\u05d5\u05dd \u05d1\u05e9\u05d1\u05d5\u05e2'),
        ),
        migrations.AlterField(
            model_name='weeklyactivity',
            name='end_date',
            field=models.DateField(verbose_name='\u05ea\u05d0\u05e8\u05d9\u05da \u05e1\u05d9\u05d5\u05dd'),
        ),
        migrations.AlterField(
            model_name='weeklyactivity',
            name='end_time',
            field=models.TimeField(verbose_name='\u05e9\u05e2\u05ea \u05e1\u05d9\u05d5\u05dd'),
        ),
        migrations.AlterField(
            model_name='weeklyactivity',
            name='start_date',
            field=models.DateField(verbose_name='\u05ea\u05d0\u05e8\u05d9\u05da \u05d4\u05ea\u05d7\u05dc\u05d4'),
        ),
        migrations.AlterField(
            model_name='weeklyactivity',
            name='start_time',
            field=models.TimeField(verbose_name='\u05e9\u05e2\u05ea \u05d4\u05ea\u05d7\u05dc\u05d4'),
        ),
    ]
